### ISSUE TITLE
Using trained data from another github

### ISSUE THREAD

**Issue by iAmPhilo** [linSensiGit/Example_Based_Manga_Colorization---cGAN#1]
Is there a way to use the trained data in the 'generator' zip from this github?

https://github.com/qweasdd/manga-colorization-v2

The colorization is pretty good on that hub, but the owner did not leave anyway to further train the data and was hoping we can use it for this.

**Comment by linshys** [comment]
I have checked the 'generator' zip you mentioned. 
It seems that the data in the 'generator' zip is not the training image dataset, but the weight data of the generator. So it can't be used for training.
And I also checked that hub doesn't leave any image dataset as well as training method.
If you want to train my model, I suggest you find some image datasets instead.
