### ISSUE TITLE
Bug whit --path and --ckpt

### ISSUE THREAD

**Issue by Keiser04** [linSensiGit/Example_Based_Manga_Colorization---cGAN#3]
If you use --path in theory you should specify the image, but it is not possible. it is used to specify the model to be used. --ckpt is used to specify the location instead of the image itself since it looks for the image in that location.
![imagen](https://github.com/linSensiGit/Example_Based_Manga_Colorization---cGAN/assets/146493916/2d5e3f91-ba06-482f-85d6-71663af3206e)
I guess it's this part of the code when assigning variables
![imagen](https://github.com/linSensiGit/Example_Based_Manga_Colorization---cGAN/assets/146493916/a98811f4-359f-4144-b28d-b9d239335341)
![imagen](https://github.com/linSensiGit/Example_Based_Manga_Colorization---cGAN/assets/146493916/d3707744-d4ea-4e5f-82e6-48961fecf34f)

**Comment by linshys** [comment]
Thanks for pointing out the bugs！
I have fixed this issue, please check update.

![image](https://github.com/linSensiGit/Example_Based_Manga_Colorization---cGAN/assets/114797928/4e210461-c25f-4fdb-82ce-fcd41ebb1c79)
